#!/bin/bash

#
# stop vms
#

function shutdownvm {
  sudo virsh shutdown "$1"
}

shutdownvm "etcd1"
shutdownvm "etcd2"
shutdownvm "etcd3"
shutdownvm "controller1"
shutdownvm "controller2"
shutdownvm "worker1"
shutdownvm "worker2"
shutdownvm "lb1"
shutdownvm "lb2"
