#!/bin/bash

function destroyvm {
  sudo virsh destroy "$1"
}

destroyvm "etcd1"
destroyvm "etcd2"
destroyvm "etcd3"
destroyvm "controller1"
destroyvm "controller2"
destroyvm "worker1"
destroyvm "worker2"
destroyvm "lb1"
destroyvm "lb2"
